use std::fmt;

#[derive(Default, Debug)]
pub struct CountsTri {
    aca: u64,
    acc: u64,
    acg: u64,
    act: u64,
    ata: u64,
    atc: u64,
    atg: u64,
    att: u64,
    cca: u64,
    ccc: u64,
    ccg: u64,
    cct: u64,
    cta: u64,
    ctc: u64,
    ctg: u64,
    ctt: u64,
    gca: u64,
    gcc: u64,
    gcg: u64,
    gct: u64,
    gta: u64,
    gtc: u64,
    gtg: u64,
    gtt: u64,
    tca: u64,
    tcc: u64,
    tcg: u64,
    tct: u64,
    tta: u64,
    ttc: u64,
    ttg: u64,
    ttt: u64,
    other: u64,
}

impl CountsTri {
    /// Increment the counter for this 3-mer.
    /// Converts trinucleotide str to lowercase, pyrimidine-centered forms (T,C)
    /// by reverse complementing purine-centered sequences.
    /// Will count non-ATCG containing sequences as 'other'
    pub fn increment(&mut self, tri: &str) {
        // Change to Uppercase
        let tri_lower = tri.to_ascii_lowercase();
        match tri_lower.as_str() {
            // Pyrimidine (C,T) Centered Contexts
            "aca" => self.aca += 1,
            "acc" => self.acc += 1,
            "acg" => self.acg += 1,
            "act" => self.act += 1,
            "ata" => self.ata += 1,
            "atc" => self.atc += 1,
            "atg" => self.atg += 1,
            "att" => self.att += 1,
            "cca" => self.cca += 1,
            "ccc" => self.ccc += 1,
            "ccg" => self.ccg += 1,
            "cct" => self.cct += 1,
            "cta" => self.cta += 1,
            "ctc" => self.ctc += 1,
            "ctg" => self.ctg += 1,
            "ctt" => self.ctt += 1,
            "gca" => self.gca += 1,
            "gcc" => self.gcc += 1,
            "gcg" => self.gcg += 1,
            "gct" => self.gct += 1,
            "gta" => self.gta += 1,
            "gtc" => self.gtc += 1,
            "gtg" => self.gtg += 1,
            "gtt" => self.gtt += 1,
            "tca" => self.tca += 1,
            "tcc" => self.tcc += 1,
            "tcg" => self.tcg += 1,
            "tct" => self.tct += 1,
            "tta" => self.tta += 1,
            "ttc" => self.ttc += 1,
            "ttg" => self.ttg += 1,
            "ttt" => self.ttt += 1,
            // Purine (A,G) Centered Contexts. Counted based on their 'pyrimidine centered form' (reverse complement)
            "aaa" => self.ttt += 1,
            "caa" => self.ttg += 1,
            "gaa" => self.ttc += 1,
            "taa" => self.tta += 1,
            "aga" => self.tct += 1,
            "cga" => self.tcg += 1,
            "gga" => self.tcc += 1,
            "tga" => self.tca += 1,
            "aac" => self.gtt += 1,
            "cac" => self.gtg += 1,
            "gac" => self.gtc += 1,
            "tac" => self.gta += 1,
            "agc" => self.gct += 1,
            "cgc" => self.gcg += 1,
            "ggc" => self.gcc += 1,
            "tgc" => self.gca += 1,
            "aag" => self.ctt += 1,
            "cag" => self.ctg += 1,
            "gag" => self.ctc += 1,
            "tag" => self.cta += 1,
            "agg" => self.cct += 1,
            "cgg" => self.ccg += 1,
            "ggg" => self.ccc += 1,
            "tgg" => self.cca += 1,
            "aat" => self.att += 1,
            "cat" => self.atg += 1,
            "gat" => self.atc += 1,
            "tat" => self.ata += 1,
            "agt" => self.act += 1,
            "cgt" => self.acg += 1,
            "ggt" => self.acc += 1,
            "tgt" => self.aca += 1,
            _ => self.other += 1,
        }
    }

    /// Total mutations
    pub fn total(&self, include_other: bool) -> u64 {
        let mut total = self.aca
            + self.acc
            + self.acg
            + self.act
            + self.ata
            + self.atc
            + self.atg
            + self.att
            + self.cca
            + self.ccc
            + self.ccg
            + self.cct
            + self.cta
            + self.ctc
            + self.ctg
            + self.ctt
            + self.gca
            + self.gcc
            + self.gcg
            + self.gct
            + self.gta
            + self.gtc
            + self.gtg
            + self.gtt
            + self.tca
            + self.tcc
            + self.tcg
            + self.tct
            + self.tta
            + self.ttc
            + self.ttg
            + self.ttt;

        if include_other {
            total += self.other;
        }

        total
    }

    /// Core printer: writes a two-column table with the given delimiter
    pub fn fmt_with_delimiter(&self, f: &mut fmt::Formatter<'_>, delim: char) -> fmt::Result {
        // header
        writeln!(f, "context{d}count", d = delim)?;

        // contexts in the same order as your fields
        let pairs = [
            ("ACA", self.aca),
            ("ACC", self.acc),
            ("ACG", self.acg),
            ("ACT", self.act),
            ("ATA", self.ata),
            ("ATC", self.atc),
            ("ATG", self.atg),
            ("ATT", self.att),
            ("CCA", self.cca),
            ("CCC", self.ccc),
            ("CCG", self.ccg),
            ("CCT", self.cct),
            ("CTA", self.cta),
            ("CTC", self.ctc),
            ("CTG", self.ctg),
            ("CTT", self.ctt),
            ("GCA", self.gca),
            ("GCC", self.gcc),
            ("GCG", self.gcg),
            ("GCT", self.gct),
            ("GTA", self.gta),
            ("GTC", self.gtc),
            ("GTG", self.gtg),
            ("GTT", self.gtt),
            ("TCA", self.tca),
            ("TCC", self.tcc),
            ("TCG", self.tcg),
            ("TCT", self.tct),
            ("TTA", self.tta),
            ("TTC", self.ttc),
            ("TTG", self.ttg),
            ("TTT", self.ttt),
            ("other", self.other),
        ];

        for &(ctx, cnt) in &pairs {
            writeln!(f, "{ctx}{d}{cnt}", d = delim)?;
        }
        Ok(())
    }
}

impl fmt::Display for CountsTri {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // default to tab-delimited
        self.fmt_with_delimiter(f, '\t')
    }
}

#[derive(Default, Debug)]
pub struct CountsPenta {
    aacaa: u64,
    aacac: u64,
    aacag: u64,
    aacat: u64,
    aacca: u64,
    aaccc: u64,
    aaccg: u64,
    aacct: u64,
    aacga: u64,
    aacgc: u64,
    aacgg: u64,
    aacgt: u64,
    aacta: u64,
    aactc: u64,
    aactg: u64,
    aactt: u64,
    aataa: u64,
    aatac: u64,
    aatag: u64,
    aatat: u64,
    aatca: u64,
    aatcc: u64,
    aatcg: u64,
    aatct: u64,
    aatga: u64,
    aatgc: u64,
    aatgg: u64,
    aatgt: u64,
    aatta: u64,
    aattc: u64,
    aattg: u64,
    aattt: u64,
    accaa: u64,
    accac: u64,
    accag: u64,
    accat: u64,
    accca: u64,
    acccc: u64,
    acccg: u64,
    accct: u64,
    accga: u64,
    accgc: u64,
    accgg: u64,
    accgt: u64,
    accta: u64,
    acctc: u64,
    acctg: u64,
    acctt: u64,
    actaa: u64,
    actac: u64,
    actag: u64,
    actat: u64,
    actca: u64,
    actcc: u64,
    actcg: u64,
    actct: u64,
    actga: u64,
    actgc: u64,
    actgg: u64,
    actgt: u64,
    actta: u64,
    acttc: u64,
    acttg: u64,
    acttt: u64,
    agcaa: u64,
    agcac: u64,
    agcag: u64,
    agcat: u64,
    agcca: u64,
    agccc: u64,
    agccg: u64,
    agcct: u64,
    agcga: u64,
    agcgc: u64,
    agcgg: u64,
    agcgt: u64,
    agcta: u64,
    agctc: u64,
    agctg: u64,
    agctt: u64,
    agtaa: u64,
    agtac: u64,
    agtag: u64,
    agtat: u64,
    agtca: u64,
    agtcc: u64,
    agtcg: u64,
    agtct: u64,
    agtga: u64,
    agtgc: u64,
    agtgg: u64,
    agtgt: u64,
    agtta: u64,
    agttc: u64,
    agttg: u64,
    agttt: u64,
    atcaa: u64,
    atcac: u64,
    atcag: u64,
    atcat: u64,
    atcca: u64,
    atccc: u64,
    atccg: u64,
    atcct: u64,
    atcga: u64,
    atcgc: u64,
    atcgg: u64,
    atcgt: u64,
    atcta: u64,
    atctc: u64,
    atctg: u64,
    atctt: u64,
    attaa: u64,
    attac: u64,
    attag: u64,
    attat: u64,
    attca: u64,
    attcc: u64,
    attcg: u64,
    attct: u64,
    attga: u64,
    attgc: u64,
    attgg: u64,
    attgt: u64,
    attta: u64,
    atttc: u64,
    atttg: u64,
    atttt: u64,
    cacaa: u64,
    cacac: u64,
    cacag: u64,
    cacat: u64,
    cacca: u64,
    caccc: u64,
    caccg: u64,
    cacct: u64,
    cacga: u64,
    cacgc: u64,
    cacgg: u64,
    cacgt: u64,
    cacta: u64,
    cactc: u64,
    cactg: u64,
    cactt: u64,
    cataa: u64,
    catac: u64,
    catag: u64,
    catat: u64,
    catca: u64,
    catcc: u64,
    catcg: u64,
    catct: u64,
    catga: u64,
    catgc: u64,
    catgg: u64,
    catgt: u64,
    catta: u64,
    cattc: u64,
    cattg: u64,
    cattt: u64,
    cccaa: u64,
    cccac: u64,
    cccag: u64,
    cccat: u64,
    cccca: u64,
    ccccc: u64,
    ccccg: u64,
    cccct: u64,
    cccga: u64,
    cccgc: u64,
    cccgg: u64,
    cccgt: u64,
    cccta: u64,
    ccctc: u64,
    ccctg: u64,
    ccctt: u64,
    cctaa: u64,
    cctac: u64,
    cctag: u64,
    cctat: u64,
    cctca: u64,
    cctcc: u64,
    cctcg: u64,
    cctct: u64,
    cctga: u64,
    cctgc: u64,
    cctgg: u64,
    cctgt: u64,
    cctta: u64,
    ccttc: u64,
    ccttg: u64,
    ccttt: u64,
    cgcaa: u64,
    cgcac: u64,
    cgcag: u64,
    cgcat: u64,
    cgcca: u64,
    cgccc: u64,
    cgccg: u64,
    cgcct: u64,
    cgcga: u64,
    cgcgc: u64,
    cgcgg: u64,
    cgcgt: u64,
    cgcta: u64,
    cgctc: u64,
    cgctg: u64,
    cgctt: u64,
    cgtaa: u64,
    cgtac: u64,
    cgtag: u64,
    cgtat: u64,
    cgtca: u64,
    cgtcc: u64,
    cgtcg: u64,
    cgtct: u64,
    cgtga: u64,
    cgtgc: u64,
    cgtgg: u64,
    cgtgt: u64,
    cgtta: u64,
    cgttc: u64,
    cgttg: u64,
    cgttt: u64,
    ctcaa: u64,
    ctcac: u64,
    ctcag: u64,
    ctcat: u64,
    ctcca: u64,
    ctccc: u64,
    ctccg: u64,
    ctcct: u64,
    ctcga: u64,
    ctcgc: u64,
    ctcgg: u64,
    ctcgt: u64,
    ctcta: u64,
    ctctc: u64,
    ctctg: u64,
    ctctt: u64,
    cttaa: u64,
    cttac: u64,
    cttag: u64,
    cttat: u64,
    cttca: u64,
    cttcc: u64,
    cttcg: u64,
    cttct: u64,
    cttga: u64,
    cttgc: u64,
    cttgg: u64,
    cttgt: u64,
    cttta: u64,
    ctttc: u64,
    ctttg: u64,
    ctttt: u64,
    gacaa: u64,
    gacac: u64,
    gacag: u64,
    gacat: u64,
    gacca: u64,
    gaccc: u64,
    gaccg: u64,
    gacct: u64,
    gacga: u64,
    gacgc: u64,
    gacgg: u64,
    gacgt: u64,
    gacta: u64,
    gactc: u64,
    gactg: u64,
    gactt: u64,
    gataa: u64,
    gatac: u64,
    gatag: u64,
    gatat: u64,
    gatca: u64,
    gatcc: u64,
    gatcg: u64,
    gatct: u64,
    gatga: u64,
    gatgc: u64,
    gatgg: u64,
    gatgt: u64,
    gatta: u64,
    gattc: u64,
    gattg: u64,
    gattt: u64,
    gccaa: u64,
    gccac: u64,
    gccag: u64,
    gccat: u64,
    gccca: u64,
    gcccc: u64,
    gcccg: u64,
    gccct: u64,
    gccga: u64,
    gccgc: u64,
    gccgg: u64,
    gccgt: u64,
    gccta: u64,
    gcctc: u64,
    gcctg: u64,
    gcctt: u64,
    gctaa: u64,
    gctac: u64,
    gctag: u64,
    gctat: u64,
    gctca: u64,
    gctcc: u64,
    gctcg: u64,
    gctct: u64,
    gctga: u64,
    gctgc: u64,
    gctgg: u64,
    gctgt: u64,
    gctta: u64,
    gcttc: u64,
    gcttg: u64,
    gcttt: u64,
    ggcaa: u64,
    ggcac: u64,
    ggcag: u64,
    ggcat: u64,
    ggcca: u64,
    ggccc: u64,
    ggccg: u64,
    ggcct: u64,
    ggcga: u64,
    ggcgc: u64,
    ggcgg: u64,
    ggcgt: u64,
    ggcta: u64,
    ggctc: u64,
    ggctg: u64,
    ggctt: u64,
    ggtaa: u64,
    ggtac: u64,
    ggtag: u64,
    ggtat: u64,
    ggtca: u64,
    ggtcc: u64,
    ggtcg: u64,
    ggtct: u64,
    ggtga: u64,
    ggtgc: u64,
    ggtgg: u64,
    ggtgt: u64,
    ggtta: u64,
    ggttc: u64,
    ggttg: u64,
    ggttt: u64,
    gtcaa: u64,
    gtcac: u64,
    gtcag: u64,
    gtcat: u64,
    gtcca: u64,
    gtccc: u64,
    gtccg: u64,
    gtcct: u64,
    gtcga: u64,
    gtcgc: u64,
    gtcgg: u64,
    gtcgt: u64,
    gtcta: u64,
    gtctc: u64,
    gtctg: u64,
    gtctt: u64,
    gttaa: u64,
    gttac: u64,
    gttag: u64,
    gttat: u64,
    gttca: u64,
    gttcc: u64,
    gttcg: u64,
    gttct: u64,
    gttga: u64,
    gttgc: u64,
    gttgg: u64,
    gttgt: u64,
    gttta: u64,
    gtttc: u64,
    gtttg: u64,
    gtttt: u64,
    tacaa: u64,
    tacac: u64,
    tacag: u64,
    tacat: u64,
    tacca: u64,
    taccc: u64,
    taccg: u64,
    tacct: u64,
    tacga: u64,
    tacgc: u64,
    tacgg: u64,
    tacgt: u64,
    tacta: u64,
    tactc: u64,
    tactg: u64,
    tactt: u64,
    tataa: u64,
    tatac: u64,
    tatag: u64,
    tatat: u64,
    tatca: u64,
    tatcc: u64,
    tatcg: u64,
    tatct: u64,
    tatga: u64,
    tatgc: u64,
    tatgg: u64,
    tatgt: u64,
    tatta: u64,
    tattc: u64,
    tattg: u64,
    tattt: u64,
    tccaa: u64,
    tccac: u64,
    tccag: u64,
    tccat: u64,
    tccca: u64,
    tcccc: u64,
    tcccg: u64,
    tccct: u64,
    tccga: u64,
    tccgc: u64,
    tccgg: u64,
    tccgt: u64,
    tccta: u64,
    tcctc: u64,
    tcctg: u64,
    tcctt: u64,
    tctaa: u64,
    tctac: u64,
    tctag: u64,
    tctat: u64,
    tctca: u64,
    tctcc: u64,
    tctcg: u64,
    tctct: u64,
    tctga: u64,
    tctgc: u64,
    tctgg: u64,
    tctgt: u64,
    tctta: u64,
    tcttc: u64,
    tcttg: u64,
    tcttt: u64,
    tgcaa: u64,
    tgcac: u64,
    tgcag: u64,
    tgcat: u64,
    tgcca: u64,
    tgccc: u64,
    tgccg: u64,
    tgcct: u64,
    tgcga: u64,
    tgcgc: u64,
    tgcgg: u64,
    tgcgt: u64,
    tgcta: u64,
    tgctc: u64,
    tgctg: u64,
    tgctt: u64,
    tgtaa: u64,
    tgtac: u64,
    tgtag: u64,
    tgtat: u64,
    tgtca: u64,
    tgtcc: u64,
    tgtcg: u64,
    tgtct: u64,
    tgtga: u64,
    tgtgc: u64,
    tgtgg: u64,
    tgtgt: u64,
    tgtta: u64,
    tgttc: u64,
    tgttg: u64,
    tgttt: u64,
    ttcaa: u64,
    ttcac: u64,
    ttcag: u64,
    ttcat: u64,
    ttcca: u64,
    ttccc: u64,
    ttccg: u64,
    ttcct: u64,
    ttcga: u64,
    ttcgc: u64,
    ttcgg: u64,
    ttcgt: u64,
    ttcta: u64,
    ttctc: u64,
    ttctg: u64,
    ttctt: u64,
    tttaa: u64,
    tttac: u64,
    tttag: u64,
    tttat: u64,
    tttca: u64,
    tttcc: u64,
    tttcg: u64,
    tttct: u64,
    tttga: u64,
    tttgc: u64,
    tttgg: u64,
    tttgt: u64,
    tttta: u64,
    ttttc: u64,
    ttttg: u64,
    ttttt: u64,
    other: u64,
}

impl CountsPenta {
    pub fn increment(&mut self, penta: &str) {
        // Change to Uppercase
        let penta = penta.to_ascii_lowercase();
        match penta.as_str() {
            // Pyrimidine (C,T) Centered Contexts
            "aacaa" => self.aacaa += 1,
            "aacac" => self.aacac += 1,
            "aacag" => self.aacag += 1,
            "aacat" => self.aacat += 1,
            "aacca" => self.aacca += 1,
            "aaccc" => self.aaccc += 1,
            "aaccg" => self.aaccg += 1,
            "aacct" => self.aacct += 1,
            "aacga" => self.aacga += 1,
            "aacgc" => self.aacgc += 1,
            "aacgg" => self.aacgg += 1,
            "aacgt" => self.aacgt += 1,
            "aacta" => self.aacta += 1,
            "aactc" => self.aactc += 1,
            "aactg" => self.aactg += 1,
            "aactt" => self.aactt += 1,
            "aataa" => self.aataa += 1,
            "aatac" => self.aatac += 1,
            "aatag" => self.aatag += 1,
            "aatat" => self.aatat += 1,
            "aatca" => self.aatca += 1,
            "aatcc" => self.aatcc += 1,
            "aatcg" => self.aatcg += 1,
            "aatct" => self.aatct += 1,
            "aatga" => self.aatga += 1,
            "aatgc" => self.aatgc += 1,
            "aatgg" => self.aatgg += 1,
            "aatgt" => self.aatgt += 1,
            "aatta" => self.aatta += 1,
            "aattc" => self.aattc += 1,
            "aattg" => self.aattg += 1,
            "aattt" => self.aattt += 1,
            "accaa" => self.accaa += 1,
            "accac" => self.accac += 1,
            "accag" => self.accag += 1,
            "accat" => self.accat += 1,
            "accca" => self.accca += 1,
            "acccc" => self.acccc += 1,
            "acccg" => self.acccg += 1,
            "accct" => self.accct += 1,
            "accga" => self.accga += 1,
            "accgc" => self.accgc += 1,
            "accgg" => self.accgg += 1,
            "accgt" => self.accgt += 1,
            "accta" => self.accta += 1,
            "acctc" => self.acctc += 1,
            "acctg" => self.acctg += 1,
            "acctt" => self.acctt += 1,
            "actaa" => self.actaa += 1,
            "actac" => self.actac += 1,
            "actag" => self.actag += 1,
            "actat" => self.actat += 1,
            "actca" => self.actca += 1,
            "actcc" => self.actcc += 1,
            "actcg" => self.actcg += 1,
            "actct" => self.actct += 1,
            "actga" => self.actga += 1,
            "actgc" => self.actgc += 1,
            "actgg" => self.actgg += 1,
            "actgt" => self.actgt += 1,
            "actta" => self.actta += 1,
            "acttc" => self.acttc += 1,
            "acttg" => self.acttg += 1,
            "acttt" => self.acttt += 1,
            "agcaa" => self.agcaa += 1,
            "agcac" => self.agcac += 1,
            "agcag" => self.agcag += 1,
            "agcat" => self.agcat += 1,
            "agcca" => self.agcca += 1,
            "agccc" => self.agccc += 1,
            "agccg" => self.agccg += 1,
            "agcct" => self.agcct += 1,
            "agcga" => self.agcga += 1,
            "agcgc" => self.agcgc += 1,
            "agcgg" => self.agcgg += 1,
            "agcgt" => self.agcgt += 1,
            "agcta" => self.agcta += 1,
            "agctc" => self.agctc += 1,
            "agctg" => self.agctg += 1,
            "agctt" => self.agctt += 1,
            "agtaa" => self.agtaa += 1,
            "agtac" => self.agtac += 1,
            "agtag" => self.agtag += 1,
            "agtat" => self.agtat += 1,
            "agtca" => self.agtca += 1,
            "agtcc" => self.agtcc += 1,
            "agtcg" => self.agtcg += 1,
            "agtct" => self.agtct += 1,
            "agtga" => self.agtga += 1,
            "agtgc" => self.agtgc += 1,
            "agtgg" => self.agtgg += 1,
            "agtgt" => self.agtgt += 1,
            "agtta" => self.agtta += 1,
            "agttc" => self.agttc += 1,
            "agttg" => self.agttg += 1,
            "agttt" => self.agttt += 1,
            "atcaa" => self.atcaa += 1,
            "atcac" => self.atcac += 1,
            "atcag" => self.atcag += 1,
            "atcat" => self.atcat += 1,
            "atcca" => self.atcca += 1,
            "atccc" => self.atccc += 1,
            "atccg" => self.atccg += 1,
            "atcct" => self.atcct += 1,
            "atcga" => self.atcga += 1,
            "atcgc" => self.atcgc += 1,
            "atcgg" => self.atcgg += 1,
            "atcgt" => self.atcgt += 1,
            "atcta" => self.atcta += 1,
            "atctc" => self.atctc += 1,
            "atctg" => self.atctg += 1,
            "atctt" => self.atctt += 1,
            "attaa" => self.attaa += 1,
            "attac" => self.attac += 1,
            "attag" => self.attag += 1,
            "attat" => self.attat += 1,
            "attca" => self.attca += 1,
            "attcc" => self.attcc += 1,
            "attcg" => self.attcg += 1,
            "attct" => self.attct += 1,
            "attga" => self.attga += 1,
            "attgc" => self.attgc += 1,
            "attgg" => self.attgg += 1,
            "attgt" => self.attgt += 1,
            "attta" => self.attta += 1,
            "atttc" => self.atttc += 1,
            "atttg" => self.atttg += 1,
            "atttt" => self.atttt += 1,
            "cacaa" => self.cacaa += 1,
            "cacac" => self.cacac += 1,
            "cacag" => self.cacag += 1,
            "cacat" => self.cacat += 1,
            "cacca" => self.cacca += 1,
            "caccc" => self.caccc += 1,
            "caccg" => self.caccg += 1,
            "cacct" => self.cacct += 1,
            "cacga" => self.cacga += 1,
            "cacgc" => self.cacgc += 1,
            "cacgg" => self.cacgg += 1,
            "cacgt" => self.cacgt += 1,
            "cacta" => self.cacta += 1,
            "cactc" => self.cactc += 1,
            "cactg" => self.cactg += 1,
            "cactt" => self.cactt += 1,
            "cataa" => self.cataa += 1,
            "catac" => self.catac += 1,
            "catag" => self.catag += 1,
            "catat" => self.catat += 1,
            "catca" => self.catca += 1,
            "catcc" => self.catcc += 1,
            "catcg" => self.catcg += 1,
            "catct" => self.catct += 1,
            "catga" => self.catga += 1,
            "catgc" => self.catgc += 1,
            "catgg" => self.catgg += 1,
            "catgt" => self.catgt += 1,
            "catta" => self.catta += 1,
            "cattc" => self.cattc += 1,
            "cattg" => self.cattg += 1,
            "cattt" => self.cattt += 1,
            "cccaa" => self.cccaa += 1,
            "cccac" => self.cccac += 1,
            "cccag" => self.cccag += 1,
            "cccat" => self.cccat += 1,
            "cccca" => self.cccca += 1,
            "ccccc" => self.ccccc += 1,
            "ccccg" => self.ccccg += 1,
            "cccct" => self.cccct += 1,
            "cccga" => self.cccga += 1,
            "cccgc" => self.cccgc += 1,
            "cccgg" => self.cccgg += 1,
            "cccgt" => self.cccgt += 1,
            "cccta" => self.cccta += 1,
            "ccctc" => self.ccctc += 1,
            "ccctg" => self.ccctg += 1,
            "ccctt" => self.ccctt += 1,
            "cctaa" => self.cctaa += 1,
            "cctac" => self.cctac += 1,
            "cctag" => self.cctag += 1,
            "cctat" => self.cctat += 1,
            "cctca" => self.cctca += 1,
            "cctcc" => self.cctcc += 1,
            "cctcg" => self.cctcg += 1,
            "cctct" => self.cctct += 1,
            "cctga" => self.cctga += 1,
            "cctgc" => self.cctgc += 1,
            "cctgg" => self.cctgg += 1,
            "cctgt" => self.cctgt += 1,
            "cctta" => self.cctta += 1,
            "ccttc" => self.ccttc += 1,
            "ccttg" => self.ccttg += 1,
            "ccttt" => self.ccttt += 1,
            "cgcaa" => self.cgcaa += 1,
            "cgcac" => self.cgcac += 1,
            "cgcag" => self.cgcag += 1,
            "cgcat" => self.cgcat += 1,
            "cgcca" => self.cgcca += 1,
            "cgccc" => self.cgccc += 1,
            "cgccg" => self.cgccg += 1,
            "cgcct" => self.cgcct += 1,
            "cgcga" => self.cgcga += 1,
            "cgcgc" => self.cgcgc += 1,
            "cgcgg" => self.cgcgg += 1,
            "cgcgt" => self.cgcgt += 1,
            "cgcta" => self.cgcta += 1,
            "cgctc" => self.cgctc += 1,
            "cgctg" => self.cgctg += 1,
            "cgctt" => self.cgctt += 1,
            "cgtaa" => self.cgtaa += 1,
            "cgtac" => self.cgtac += 1,
            "cgtag" => self.cgtag += 1,
            "cgtat" => self.cgtat += 1,
            "cgtca" => self.cgtca += 1,
            "cgtcc" => self.cgtcc += 1,
            "cgtcg" => self.cgtcg += 1,
            "cgtct" => self.cgtct += 1,
            "cgtga" => self.cgtga += 1,
            "cgtgc" => self.cgtgc += 1,
            "cgtgg" => self.cgtgg += 1,
            "cgtgt" => self.cgtgt += 1,
            "cgtta" => self.cgtta += 1,
            "cgttc" => self.cgttc += 1,
            "cgttg" => self.cgttg += 1,
            "cgttt" => self.cgttt += 1,
            "ctcaa" => self.ctcaa += 1,
            "ctcac" => self.ctcac += 1,
            "ctcag" => self.ctcag += 1,
            "ctcat" => self.ctcat += 1,
            "ctcca" => self.ctcca += 1,
            "ctccc" => self.ctccc += 1,
            "ctccg" => self.ctccg += 1,
            "ctcct" => self.ctcct += 1,
            "ctcga" => self.ctcga += 1,
            "ctcgc" => self.ctcgc += 1,
            "ctcgg" => self.ctcgg += 1,
            "ctcgt" => self.ctcgt += 1,
            "ctcta" => self.ctcta += 1,
            "ctctc" => self.ctctc += 1,
            "ctctg" => self.ctctg += 1,
            "ctctt" => self.ctctt += 1,
            "cttaa" => self.cttaa += 1,
            "cttac" => self.cttac += 1,
            "cttag" => self.cttag += 1,
            "cttat" => self.cttat += 1,
            "cttca" => self.cttca += 1,
            "cttcc" => self.cttcc += 1,
            "cttcg" => self.cttcg += 1,
            "cttct" => self.cttct += 1,
            "cttga" => self.cttga += 1,
            "cttgc" => self.cttgc += 1,
            "cttgg" => self.cttgg += 1,
            "cttgt" => self.cttgt += 1,
            "cttta" => self.cttta += 1,
            "ctttc" => self.ctttc += 1,
            "ctttg" => self.ctttg += 1,
            "ctttt" => self.ctttt += 1,
            "gacaa" => self.gacaa += 1,
            "gacac" => self.gacac += 1,
            "gacag" => self.gacag += 1,
            "gacat" => self.gacat += 1,
            "gacca" => self.gacca += 1,
            "gaccc" => self.gaccc += 1,
            "gaccg" => self.gaccg += 1,
            "gacct" => self.gacct += 1,
            "gacga" => self.gacga += 1,
            "gacgc" => self.gacgc += 1,
            "gacgg" => self.gacgg += 1,
            "gacgt" => self.gacgt += 1,
            "gacta" => self.gacta += 1,
            "gactc" => self.gactc += 1,
            "gactg" => self.gactg += 1,
            "gactt" => self.gactt += 1,
            "gataa" => self.gataa += 1,
            "gatac" => self.gatac += 1,
            "gatag" => self.gatag += 1,
            "gatat" => self.gatat += 1,
            "gatca" => self.gatca += 1,
            "gatcc" => self.gatcc += 1,
            "gatcg" => self.gatcg += 1,
            "gatct" => self.gatct += 1,
            "gatga" => self.gatga += 1,
            "gatgc" => self.gatgc += 1,
            "gatgg" => self.gatgg += 1,
            "gatgt" => self.gatgt += 1,
            "gatta" => self.gatta += 1,
            "gattc" => self.gattc += 1,
            "gattg" => self.gattg += 1,
            "gattt" => self.gattt += 1,
            "gccaa" => self.gccaa += 1,
            "gccac" => self.gccac += 1,
            "gccag" => self.gccag += 1,
            "gccat" => self.gccat += 1,
            "gccca" => self.gccca += 1,
            "gcccc" => self.gcccc += 1,
            "gcccg" => self.gcccg += 1,
            "gccct" => self.gccct += 1,
            "gccga" => self.gccga += 1,
            "gccgc" => self.gccgc += 1,
            "gccgg" => self.gccgg += 1,
            "gccgt" => self.gccgt += 1,
            "gccta" => self.gccta += 1,
            "gcctc" => self.gcctc += 1,
            "gcctg" => self.gcctg += 1,
            "gcctt" => self.gcctt += 1,
            "gctaa" => self.gctaa += 1,
            "gctac" => self.gctac += 1,
            "gctag" => self.gctag += 1,
            "gctat" => self.gctat += 1,
            "gctca" => self.gctca += 1,
            "gctcc" => self.gctcc += 1,
            "gctcg" => self.gctcg += 1,
            "gctct" => self.gctct += 1,
            "gctga" => self.gctga += 1,
            "gctgc" => self.gctgc += 1,
            "gctgg" => self.gctgg += 1,
            "gctgt" => self.gctgt += 1,
            "gctta" => self.gctta += 1,
            "gcttc" => self.gcttc += 1,
            "gcttg" => self.gcttg += 1,
            "gcttt" => self.gcttt += 1,
            "ggcaa" => self.ggcaa += 1,
            "ggcac" => self.ggcac += 1,
            "ggcag" => self.ggcag += 1,
            "ggcat" => self.ggcat += 1,
            "ggcca" => self.ggcca += 1,
            "ggccc" => self.ggccc += 1,
            "ggccg" => self.ggccg += 1,
            "ggcct" => self.ggcct += 1,
            "ggcga" => self.ggcga += 1,
            "ggcgc" => self.ggcgc += 1,
            "ggcgg" => self.ggcgg += 1,
            "ggcgt" => self.ggcgt += 1,
            "ggcta" => self.ggcta += 1,
            "ggctc" => self.ggctc += 1,
            "ggctg" => self.ggctg += 1,
            "ggctt" => self.ggctt += 1,
            "ggtaa" => self.ggtaa += 1,
            "ggtac" => self.ggtac += 1,
            "ggtag" => self.ggtag += 1,
            "ggtat" => self.ggtat += 1,
            "ggtca" => self.ggtca += 1,
            "ggtcc" => self.ggtcc += 1,
            "ggtcg" => self.ggtcg += 1,
            "ggtct" => self.ggtct += 1,
            "ggtga" => self.ggtga += 1,
            "ggtgc" => self.ggtgc += 1,
            "ggtgg" => self.ggtgg += 1,
            "ggtgt" => self.ggtgt += 1,
            "ggtta" => self.ggtta += 1,
            "ggttc" => self.ggttc += 1,
            "ggttg" => self.ggttg += 1,
            "ggttt" => self.ggttt += 1,
            "gtcaa" => self.gtcaa += 1,
            "gtcac" => self.gtcac += 1,
            "gtcag" => self.gtcag += 1,
            "gtcat" => self.gtcat += 1,
            "gtcca" => self.gtcca += 1,
            "gtccc" => self.gtccc += 1,
            "gtccg" => self.gtccg += 1,
            "gtcct" => self.gtcct += 1,
            "gtcga" => self.gtcga += 1,
            "gtcgc" => self.gtcgc += 1,
            "gtcgg" => self.gtcgg += 1,
            "gtcgt" => self.gtcgt += 1,
            "gtcta" => self.gtcta += 1,
            "gtctc" => self.gtctc += 1,
            "gtctg" => self.gtctg += 1,
            "gtctt" => self.gtctt += 1,
            "gttaa" => self.gttaa += 1,
            "gttac" => self.gttac += 1,
            "gttag" => self.gttag += 1,
            "gttat" => self.gttat += 1,
            "gttca" => self.gttca += 1,
            "gttcc" => self.gttcc += 1,
            "gttcg" => self.gttcg += 1,
            "gttct" => self.gttct += 1,
            "gttga" => self.gttga += 1,
            "gttgc" => self.gttgc += 1,
            "gttgg" => self.gttgg += 1,
            "gttgt" => self.gttgt += 1,
            "gttta" => self.gttta += 1,
            "gtttc" => self.gtttc += 1,
            "gtttg" => self.gtttg += 1,
            "gtttt" => self.gtttt += 1,
            "tacaa" => self.tacaa += 1,
            "tacac" => self.tacac += 1,
            "tacag" => self.tacag += 1,
            "tacat" => self.tacat += 1,
            "tacca" => self.tacca += 1,
            "taccc" => self.taccc += 1,
            "taccg" => self.taccg += 1,
            "tacct" => self.tacct += 1,
            "tacga" => self.tacga += 1,
            "tacgc" => self.tacgc += 1,
            "tacgg" => self.tacgg += 1,
            "tacgt" => self.tacgt += 1,
            "tacta" => self.tacta += 1,
            "tactc" => self.tactc += 1,
            "tactg" => self.tactg += 1,
            "tactt" => self.tactt += 1,
            "tataa" => self.tataa += 1,
            "tatac" => self.tatac += 1,
            "tatag" => self.tatag += 1,
            "tatat" => self.tatat += 1,
            "tatca" => self.tatca += 1,
            "tatcc" => self.tatcc += 1,
            "tatcg" => self.tatcg += 1,
            "tatct" => self.tatct += 1,
            "tatga" => self.tatga += 1,
            "tatgc" => self.tatgc += 1,
            "tatgg" => self.tatgg += 1,
            "tatgt" => self.tatgt += 1,
            "tatta" => self.tatta += 1,
            "tattc" => self.tattc += 1,
            "tattg" => self.tattg += 1,
            "tattt" => self.tattt += 1,
            "tccaa" => self.tccaa += 1,
            "tccac" => self.tccac += 1,
            "tccag" => self.tccag += 1,
            "tccat" => self.tccat += 1,
            "tccca" => self.tccca += 1,
            "tcccc" => self.tcccc += 1,
            "tcccg" => self.tcccg += 1,
            "tccct" => self.tccct += 1,
            "tccga" => self.tccga += 1,
            "tccgc" => self.tccgc += 1,
            "tccgg" => self.tccgg += 1,
            "tccgt" => self.tccgt += 1,
            "tccta" => self.tccta += 1,
            "tcctc" => self.tcctc += 1,
            "tcctg" => self.tcctg += 1,
            "tcctt" => self.tcctt += 1,
            "tctaa" => self.tctaa += 1,
            "tctac" => self.tctac += 1,
            "tctag" => self.tctag += 1,
            "tctat" => self.tctat += 1,
            "tctca" => self.tctca += 1,
            "tctcc" => self.tctcc += 1,
            "tctcg" => self.tctcg += 1,
            "tctct" => self.tctct += 1,
            "tctga" => self.tctga += 1,
            "tctgc" => self.tctgc += 1,
            "tctgg" => self.tctgg += 1,
            "tctgt" => self.tctgt += 1,
            "tctta" => self.tctta += 1,
            "tcttc" => self.tcttc += 1,
            "tcttg" => self.tcttg += 1,
            "tcttt" => self.tcttt += 1,
            "tgcaa" => self.tgcaa += 1,
            "tgcac" => self.tgcac += 1,
            "tgcag" => self.tgcag += 1,
            "tgcat" => self.tgcat += 1,
            "tgcca" => self.tgcca += 1,
            "tgccc" => self.tgccc += 1,
            "tgccg" => self.tgccg += 1,
            "tgcct" => self.tgcct += 1,
            "tgcga" => self.tgcga += 1,
            "tgcgc" => self.tgcgc += 1,
            "tgcgg" => self.tgcgg += 1,
            "tgcgt" => self.tgcgt += 1,
            "tgcta" => self.tgcta += 1,
            "tgctc" => self.tgctc += 1,
            "tgctg" => self.tgctg += 1,
            "tgctt" => self.tgctt += 1,
            "tgtaa" => self.tgtaa += 1,
            "tgtac" => self.tgtac += 1,
            "tgtag" => self.tgtag += 1,
            "tgtat" => self.tgtat += 1,
            "tgtca" => self.tgtca += 1,
            "tgtcc" => self.tgtcc += 1,
            "tgtcg" => self.tgtcg += 1,
            "tgtct" => self.tgtct += 1,
            "tgtga" => self.tgtga += 1,
            "tgtgc" => self.tgtgc += 1,
            "tgtgg" => self.tgtgg += 1,
            "tgtgt" => self.tgtgt += 1,
            "tgtta" => self.tgtta += 1,
            "tgttc" => self.tgttc += 1,
            "tgttg" => self.tgttg += 1,
            "tgttt" => self.tgttt += 1,
            "ttcaa" => self.ttcaa += 1,
            "ttcac" => self.ttcac += 1,
            "ttcag" => self.ttcag += 1,
            "ttcat" => self.ttcat += 1,
            "ttcca" => self.ttcca += 1,
            "ttccc" => self.ttccc += 1,
            "ttccg" => self.ttccg += 1,
            "ttcct" => self.ttcct += 1,
            "ttcga" => self.ttcga += 1,
            "ttcgc" => self.ttcgc += 1,
            "ttcgg" => self.ttcgg += 1,
            "ttcgt" => self.ttcgt += 1,
            "ttcta" => self.ttcta += 1,
            "ttctc" => self.ttctc += 1,
            "ttctg" => self.ttctg += 1,
            "ttctt" => self.ttctt += 1,
            "tttaa" => self.tttaa += 1,
            "tttac" => self.tttac += 1,
            "tttag" => self.tttag += 1,
            "tttat" => self.tttat += 1,
            "tttca" => self.tttca += 1,
            "tttcc" => self.tttcc += 1,
            "tttcg" => self.tttcg += 1,
            "tttct" => self.tttct += 1,
            "tttga" => self.tttga += 1,
            "tttgc" => self.tttgc += 1,
            "tttgg" => self.tttgg += 1,
            "tttgt" => self.tttgt += 1,
            "tttta" => self.tttta += 1,
            "ttttc" => self.ttttc += 1,
            "ttttg" => self.ttttg += 1,
            "ttttt" => self.ttttt += 1,
            // Purine centered version
            "aaaaa" => self.ttttt += 1,
            "caaaa" => self.ttttg += 1,
            "gaaaa" => self.ttttc += 1,
            "taaaa" => self.tttta += 1,
            "acaaa" => self.tttgt += 1,
            "ccaaa" => self.tttgg += 1,
            "gcaaa" => self.tttgc += 1,
            "tcaaa" => self.tttga += 1,
            "agaaa" => self.tttct += 1,
            "cgaaa" => self.tttcg += 1,
            "ggaaa" => self.tttcc += 1,
            "tgaaa" => self.tttca += 1,
            "ataaa" => self.tttat += 1,
            "ctaaa" => self.tttag += 1,
            "gtaaa" => self.tttac += 1,
            "ttaaa" => self.tttaa += 1,
            "aagaa" => self.ttctt += 1,
            "cagaa" => self.ttctg += 1,
            "gagaa" => self.ttctc += 1,
            "tagaa" => self.ttcta += 1,
            "acgaa" => self.ttcgt += 1,
            "ccgaa" => self.ttcgg += 1,
            "gcgaa" => self.ttcgc += 1,
            "tcgaa" => self.ttcga += 1,
            "aggaa" => self.ttcct += 1,
            "cggaa" => self.ttccg += 1,
            "gggaa" => self.ttccc += 1,
            "tggaa" => self.ttcca += 1,
            "atgaa" => self.ttcat += 1,
            "ctgaa" => self.ttcag += 1,
            "gtgaa" => self.ttcac += 1,
            "ttgaa" => self.ttcaa += 1,
            "aaaca" => self.tgttt += 1,
            "caaca" => self.tgttg += 1,
            "gaaca" => self.tgttc += 1,
            "taaca" => self.tgtta += 1,
            "acaca" => self.tgtgt += 1,
            "ccaca" => self.tgtgg += 1,
            "gcaca" => self.tgtgc += 1,
            "tcaca" => self.tgtga += 1,
            "agaca" => self.tgtct += 1,
            "cgaca" => self.tgtcg += 1,
            "ggaca" => self.tgtcc += 1,
            "tgaca" => self.tgtca += 1,
            "ataca" => self.tgtat += 1,
            "ctaca" => self.tgtag += 1,
            "gtaca" => self.tgtac += 1,
            "ttaca" => self.tgtaa += 1,
            "aagca" => self.tgctt += 1,
            "cagca" => self.tgctg += 1,
            "gagca" => self.tgctc += 1,
            "tagca" => self.tgcta += 1,
            "acgca" => self.tgcgt += 1,
            "ccgca" => self.tgcgg += 1,
            "gcgca" => self.tgcgc += 1,
            "tcgca" => self.tgcga += 1,
            "aggca" => self.tgcct += 1,
            "cggca" => self.tgccg += 1,
            "gggca" => self.tgccc += 1,
            "tggca" => self.tgcca += 1,
            "atgca" => self.tgcat += 1,
            "ctgca" => self.tgcag += 1,
            "gtgca" => self.tgcac += 1,
            "ttgca" => self.tgcaa += 1,
            "aaaga" => self.tcttt += 1,
            "caaga" => self.tcttg += 1,
            "gaaga" => self.tcttc += 1,
            "taaga" => self.tctta += 1,
            "acaga" => self.tctgt += 1,
            "ccaga" => self.tctgg += 1,
            "gcaga" => self.tctgc += 1,
            "tcaga" => self.tctga += 1,
            "agaga" => self.tctct += 1,
            "cgaga" => self.tctcg += 1,
            "ggaga" => self.tctcc += 1,
            "tgaga" => self.tctca += 1,
            "ataga" => self.tctat += 1,
            "ctaga" => self.tctag += 1,
            "gtaga" => self.tctac += 1,
            "ttaga" => self.tctaa += 1,
            "aagga" => self.tcctt += 1,
            "cagga" => self.tcctg += 1,
            "gagga" => self.tcctc += 1,
            "tagga" => self.tccta += 1,
            "acgga" => self.tccgt += 1,
            "ccgga" => self.tccgg += 1,
            "gcgga" => self.tccgc += 1,
            "tcgga" => self.tccga += 1,
            "aggga" => self.tccct += 1,
            "cggga" => self.tcccg += 1,
            "gggga" => self.tcccc += 1,
            "tggga" => self.tccca += 1,
            "atgga" => self.tccat += 1,
            "ctgga" => self.tccag += 1,
            "gtgga" => self.tccac += 1,
            "ttgga" => self.tccaa += 1,
            "aaata" => self.tattt += 1,
            "caata" => self.tattg += 1,
            "gaata" => self.tattc += 1,
            "taata" => self.tatta += 1,
            "acata" => self.tatgt += 1,
            "ccata" => self.tatgg += 1,
            "gcata" => self.tatgc += 1,
            "tcata" => self.tatga += 1,
            "agata" => self.tatct += 1,
            "cgata" => self.tatcg += 1,
            "ggata" => self.tatcc += 1,
            "tgata" => self.tatca += 1,
            "atata" => self.tatat += 1,
            "ctata" => self.tatag += 1,
            "gtata" => self.tatac += 1,
            "ttata" => self.tataa += 1,
            "aagta" => self.tactt += 1,
            "cagta" => self.tactg += 1,
            "gagta" => self.tactc += 1,
            "tagta" => self.tacta += 1,
            "acgta" => self.tacgt += 1,
            "ccgta" => self.tacgg += 1,
            "gcgta" => self.tacgc += 1,
            "tcgta" => self.tacga += 1,
            "aggta" => self.tacct += 1,
            "cggta" => self.taccg += 1,
            "gggta" => self.taccc += 1,
            "tggta" => self.tacca += 1,
            "atgta" => self.tacat += 1,
            "ctgta" => self.tacag += 1,
            "gtgta" => self.tacac += 1,
            "ttgta" => self.tacaa += 1,
            "aaaac" => self.gtttt += 1,
            "caaac" => self.gtttg += 1,
            "gaaac" => self.gtttc += 1,
            "taaac" => self.gttta += 1,
            "acaac" => self.gttgt += 1,
            "ccaac" => self.gttgg += 1,
            "gcaac" => self.gttgc += 1,
            "tcaac" => self.gttga += 1,
            "agaac" => self.gttct += 1,
            "cgaac" => self.gttcg += 1,
            "ggaac" => self.gttcc += 1,
            "tgaac" => self.gttca += 1,
            "ataac" => self.gttat += 1,
            "ctaac" => self.gttag += 1,
            "gtaac" => self.gttac += 1,
            "ttaac" => self.gttaa += 1,
            "aagac" => self.gtctt += 1,
            "cagac" => self.gtctg += 1,
            "gagac" => self.gtctc += 1,
            "tagac" => self.gtcta += 1,
            "acgac" => self.gtcgt += 1,
            "ccgac" => self.gtcgg += 1,
            "gcgac" => self.gtcgc += 1,
            "tcgac" => self.gtcga += 1,
            "aggac" => self.gtcct += 1,
            "cggac" => self.gtccg += 1,
            "gggac" => self.gtccc += 1,
            "tggac" => self.gtcca += 1,
            "atgac" => self.gtcat += 1,
            "ctgac" => self.gtcag += 1,
            "gtgac" => self.gtcac += 1,
            "ttgac" => self.gtcaa += 1,
            "aaacc" => self.ggttt += 1,
            "caacc" => self.ggttg += 1,
            "gaacc" => self.ggttc += 1,
            "taacc" => self.ggtta += 1,
            "acacc" => self.ggtgt += 1,
            "ccacc" => self.ggtgg += 1,
            "gcacc" => self.ggtgc += 1,
            "tcacc" => self.ggtga += 1,
            "agacc" => self.ggtct += 1,
            "cgacc" => self.ggtcg += 1,
            "ggacc" => self.ggtcc += 1,
            "tgacc" => self.ggtca += 1,
            "atacc" => self.ggtat += 1,
            "ctacc" => self.ggtag += 1,
            "gtacc" => self.ggtac += 1,
            "ttacc" => self.ggtaa += 1,
            "aagcc" => self.ggctt += 1,
            "cagcc" => self.ggctg += 1,
            "gagcc" => self.ggctc += 1,
            "tagcc" => self.ggcta += 1,
            "acgcc" => self.ggcgt += 1,
            "ccgcc" => self.ggcgg += 1,
            "gcgcc" => self.ggcgc += 1,
            "tcgcc" => self.ggcga += 1,
            "aggcc" => self.ggcct += 1,
            "cggcc" => self.ggccg += 1,
            "gggcc" => self.ggccc += 1,
            "tggcc" => self.ggcca += 1,
            "atgcc" => self.ggcat += 1,
            "ctgcc" => self.ggcag += 1,
            "gtgcc" => self.ggcac += 1,
            "ttgcc" => self.ggcaa += 1,
            "aaagc" => self.gcttt += 1,
            "caagc" => self.gcttg += 1,
            "gaagc" => self.gcttc += 1,
            "taagc" => self.gctta += 1,
            "acagc" => self.gctgt += 1,
            "ccagc" => self.gctgg += 1,
            "gcagc" => self.gctgc += 1,
            "tcagc" => self.gctga += 1,
            "agagc" => self.gctct += 1,
            "cgagc" => self.gctcg += 1,
            "ggagc" => self.gctcc += 1,
            "tgagc" => self.gctca += 1,
            "atagc" => self.gctat += 1,
            "ctagc" => self.gctag += 1,
            "gtagc" => self.gctac += 1,
            "ttagc" => self.gctaa += 1,
            "aaggc" => self.gcctt += 1,
            "caggc" => self.gcctg += 1,
            "gaggc" => self.gcctc += 1,
            "taggc" => self.gccta += 1,
            "acggc" => self.gccgt += 1,
            "ccggc" => self.gccgg += 1,
            "gcggc" => self.gccgc += 1,
            "tcggc" => self.gccga += 1,
            "agggc" => self.gccct += 1,
            "cgggc" => self.gcccg += 1,
            "ggggc" => self.gcccc += 1,
            "tgggc" => self.gccca += 1,
            "atggc" => self.gccat += 1,
            "ctggc" => self.gccag += 1,
            "gtggc" => self.gccac += 1,
            "ttggc" => self.gccaa += 1,
            "aaatc" => self.gattt += 1,
            "caatc" => self.gattg += 1,
            "gaatc" => self.gattc += 1,
            "taatc" => self.gatta += 1,
            "acatc" => self.gatgt += 1,
            "ccatc" => self.gatgg += 1,
            "gcatc" => self.gatgc += 1,
            "tcatc" => self.gatga += 1,
            "agatc" => self.gatct += 1,
            "cgatc" => self.gatcg += 1,
            "ggatc" => self.gatcc += 1,
            "tgatc" => self.gatca += 1,
            "atatc" => self.gatat += 1,
            "ctatc" => self.gatag += 1,
            "gtatc" => self.gatac += 1,
            "ttatc" => self.gataa += 1,
            "aagtc" => self.gactt += 1,
            "cagtc" => self.gactg += 1,
            "gagtc" => self.gactc += 1,
            "tagtc" => self.gacta += 1,
            "acgtc" => self.gacgt += 1,
            "ccgtc" => self.gacgg += 1,
            "gcgtc" => self.gacgc += 1,
            "tcgtc" => self.gacga += 1,
            "aggtc" => self.gacct += 1,
            "cggtc" => self.gaccg += 1,
            "gggtc" => self.gaccc += 1,
            "tggtc" => self.gacca += 1,
            "atgtc" => self.gacat += 1,
            "ctgtc" => self.gacag += 1,
            "gtgtc" => self.gacac += 1,
            "ttgtc" => self.gacaa += 1,
            "aaaag" => self.ctttt += 1,
            "caaag" => self.ctttg += 1,
            "gaaag" => self.ctttc += 1,
            "taaag" => self.cttta += 1,
            "acaag" => self.cttgt += 1,
            "ccaag" => self.cttgg += 1,
            "gcaag" => self.cttgc += 1,
            "tcaag" => self.cttga += 1,
            "agaag" => self.cttct += 1,
            "cgaag" => self.cttcg += 1,
            "ggaag" => self.cttcc += 1,
            "tgaag" => self.cttca += 1,
            "ataag" => self.cttat += 1,
            "ctaag" => self.cttag += 1,
            "gtaag" => self.cttac += 1,
            "ttaag" => self.cttaa += 1,
            "aagag" => self.ctctt += 1,
            "cagag" => self.ctctg += 1,
            "gagag" => self.ctctc += 1,
            "tagag" => self.ctcta += 1,
            "acgag" => self.ctcgt += 1,
            "ccgag" => self.ctcgg += 1,
            "gcgag" => self.ctcgc += 1,
            "tcgag" => self.ctcga += 1,
            "aggag" => self.ctcct += 1,
            "cggag" => self.ctccg += 1,
            "gggag" => self.ctccc += 1,
            "tggag" => self.ctcca += 1,
            "atgag" => self.ctcat += 1,
            "ctgag" => self.ctcag += 1,
            "gtgag" => self.ctcac += 1,
            "ttgag" => self.ctcaa += 1,
            "aaacg" => self.cgttt += 1,
            "caacg" => self.cgttg += 1,
            "gaacg" => self.cgttc += 1,
            "taacg" => self.cgtta += 1,
            "acacg" => self.cgtgt += 1,
            "ccacg" => self.cgtgg += 1,
            "gcacg" => self.cgtgc += 1,
            "tcacg" => self.cgtga += 1,
            "agacg" => self.cgtct += 1,
            "cgacg" => self.cgtcg += 1,
            "ggacg" => self.cgtcc += 1,
            "tgacg" => self.cgtca += 1,
            "atacg" => self.cgtat += 1,
            "ctacg" => self.cgtag += 1,
            "gtacg" => self.cgtac += 1,
            "ttacg" => self.cgtaa += 1,
            "aagcg" => self.cgctt += 1,
            "cagcg" => self.cgctg += 1,
            "gagcg" => self.cgctc += 1,
            "tagcg" => self.cgcta += 1,
            "acgcg" => self.cgcgt += 1,
            "ccgcg" => self.cgcgg += 1,
            "gcgcg" => self.cgcgc += 1,
            "tcgcg" => self.cgcga += 1,
            "aggcg" => self.cgcct += 1,
            "cggcg" => self.cgccg += 1,
            "gggcg" => self.cgccc += 1,
            "tggcg" => self.cgcca += 1,
            "atgcg" => self.cgcat += 1,
            "ctgcg" => self.cgcag += 1,
            "gtgcg" => self.cgcac += 1,
            "ttgcg" => self.cgcaa += 1,
            "aaagg" => self.ccttt += 1,
            "caagg" => self.ccttg += 1,
            "gaagg" => self.ccttc += 1,
            "taagg" => self.cctta += 1,
            "acagg" => self.cctgt += 1,
            "ccagg" => self.cctgg += 1,
            "gcagg" => self.cctgc += 1,
            "tcagg" => self.cctga += 1,
            "agagg" => self.cctct += 1,
            "cgagg" => self.cctcg += 1,
            "ggagg" => self.cctcc += 1,
            "tgagg" => self.cctca += 1,
            "atagg" => self.cctat += 1,
            "ctagg" => self.cctag += 1,
            "gtagg" => self.cctac += 1,
            "ttagg" => self.cctaa += 1,
            "aaggg" => self.ccctt += 1,
            "caggg" => self.ccctg += 1,
            "gaggg" => self.ccctc += 1,
            "taggg" => self.cccta += 1,
            "acggg" => self.cccgt += 1,
            "ccggg" => self.cccgg += 1,
            "gcggg" => self.cccgc += 1,
            "tcggg" => self.cccga += 1,
            "agggg" => self.cccct += 1,
            "cgggg" => self.ccccg += 1,
            "ggggg" => self.ccccc += 1,
            "tgggg" => self.cccca += 1,
            "atggg" => self.cccat += 1,
            "ctggg" => self.cccag += 1,
            "gtggg" => self.cccac += 1,
            "ttggg" => self.cccaa += 1,
            "aaatg" => self.cattt += 1,
            "caatg" => self.cattg += 1,
            "gaatg" => self.cattc += 1,
            "taatg" => self.catta += 1,
            "acatg" => self.catgt += 1,
            "ccatg" => self.catgg += 1,
            "gcatg" => self.catgc += 1,
            "tcatg" => self.catga += 1,
            "agatg" => self.catct += 1,
            "cgatg" => self.catcg += 1,
            "ggatg" => self.catcc += 1,
            "tgatg" => self.catca += 1,
            "atatg" => self.catat += 1,
            "ctatg" => self.catag += 1,
            "gtatg" => self.catac += 1,
            "ttatg" => self.cataa += 1,
            "aagtg" => self.cactt += 1,
            "cagtg" => self.cactg += 1,
            "gagtg" => self.cactc += 1,
            "tagtg" => self.cacta += 1,
            "acgtg" => self.cacgt += 1,
            "ccgtg" => self.cacgg += 1,
            "gcgtg" => self.cacgc += 1,
            "tcgtg" => self.cacga += 1,
            "aggtg" => self.cacct += 1,
            "cggtg" => self.caccg += 1,
            "gggtg" => self.caccc += 1,
            "tggtg" => self.cacca += 1,
            "atgtg" => self.cacat += 1,
            "ctgtg" => self.cacag += 1,
            "gtgtg" => self.cacac += 1,
            "ttgtg" => self.cacaa += 1,
            "aaaat" => self.atttt += 1,
            "caaat" => self.atttg += 1,
            "gaaat" => self.atttc += 1,
            "taaat" => self.attta += 1,
            "acaat" => self.attgt += 1,
            "ccaat" => self.attgg += 1,
            "gcaat" => self.attgc += 1,
            "tcaat" => self.attga += 1,
            "agaat" => self.attct += 1,
            "cgaat" => self.attcg += 1,
            "ggaat" => self.attcc += 1,
            "tgaat" => self.attca += 1,
            "ataat" => self.attat += 1,
            "ctaat" => self.attag += 1,
            "gtaat" => self.attac += 1,
            "ttaat" => self.attaa += 1,
            "aagat" => self.atctt += 1,
            "cagat" => self.atctg += 1,
            "gagat" => self.atctc += 1,
            "tagat" => self.atcta += 1,
            "acgat" => self.atcgt += 1,
            "ccgat" => self.atcgg += 1,
            "gcgat" => self.atcgc += 1,
            "tcgat" => self.atcga += 1,
            "aggat" => self.atcct += 1,
            "cggat" => self.atccg += 1,
            "gggat" => self.atccc += 1,
            "tggat" => self.atcca += 1,
            "atgat" => self.atcat += 1,
            "ctgat" => self.atcag += 1,
            "gtgat" => self.atcac += 1,
            "ttgat" => self.atcaa += 1,
            "aaact" => self.agttt += 1,
            "caact" => self.agttg += 1,
            "gaact" => self.agttc += 1,
            "taact" => self.agtta += 1,
            "acact" => self.agtgt += 1,
            "ccact" => self.agtgg += 1,
            "gcact" => self.agtgc += 1,
            "tcact" => self.agtga += 1,
            "agact" => self.agtct += 1,
            "cgact" => self.agtcg += 1,
            "ggact" => self.agtcc += 1,
            "tgact" => self.agtca += 1,
            "atact" => self.agtat += 1,
            "ctact" => self.agtag += 1,
            "gtact" => self.agtac += 1,
            "ttact" => self.agtaa += 1,
            "aagct" => self.agctt += 1,
            "cagct" => self.agctg += 1,
            "gagct" => self.agctc += 1,
            "tagct" => self.agcta += 1,
            "acgct" => self.agcgt += 1,
            "ccgct" => self.agcgg += 1,
            "gcgct" => self.agcgc += 1,
            "tcgct" => self.agcga += 1,
            "aggct" => self.agcct += 1,
            "cggct" => self.agccg += 1,
            "gggct" => self.agccc += 1,
            "tggct" => self.agcca += 1,
            "atgct" => self.agcat += 1,
            "ctgct" => self.agcag += 1,
            "gtgct" => self.agcac += 1,
            "ttgct" => self.agcaa += 1,
            "aaagt" => self.acttt += 1,
            "caagt" => self.acttg += 1,
            "gaagt" => self.acttc += 1,
            "taagt" => self.actta += 1,
            "acagt" => self.actgt += 1,
            "ccagt" => self.actgg += 1,
            "gcagt" => self.actgc += 1,
            "tcagt" => self.actga += 1,
            "agagt" => self.actct += 1,
            "cgagt" => self.actcg += 1,
            "ggagt" => self.actcc += 1,
            "tgagt" => self.actca += 1,
            "atagt" => self.actat += 1,
            "ctagt" => self.actag += 1,
            "gtagt" => self.actac += 1,
            "ttagt" => self.actaa += 1,
            "aaggt" => self.acctt += 1,
            "caggt" => self.acctg += 1,
            "gaggt" => self.acctc += 1,
            "taggt" => self.accta += 1,
            "acggt" => self.accgt += 1,
            "ccggt" => self.accgg += 1,
            "gcggt" => self.accgc += 1,
            "tcggt" => self.accga += 1,
            "agggt" => self.accct += 1,
            "cgggt" => self.acccg += 1,
            "ggggt" => self.acccc += 1,
            "tgggt" => self.accca += 1,
            "atggt" => self.accat += 1,
            "ctggt" => self.accag += 1,
            "gtggt" => self.accac += 1,
            "ttggt" => self.accaa += 1,
            "aaatt" => self.aattt += 1,
            "caatt" => self.aattg += 1,
            "gaatt" => self.aattc += 1,
            "taatt" => self.aatta += 1,
            "acatt" => self.aatgt += 1,
            "ccatt" => self.aatgg += 1,
            "gcatt" => self.aatgc += 1,
            "tcatt" => self.aatga += 1,
            "agatt" => self.aatct += 1,
            "cgatt" => self.aatcg += 1,
            "ggatt" => self.aatcc += 1,
            "tgatt" => self.aatca += 1,
            "atatt" => self.aatat += 1,
            "ctatt" => self.aatag += 1,
            "gtatt" => self.aatac += 1,
            "ttatt" => self.aataa += 1,
            "aagtt" => self.aactt += 1,
            "cagtt" => self.aactg += 1,
            "gagtt" => self.aactc += 1,
            "tagtt" => self.aacta += 1,
            "acgtt" => self.aacgt += 1,
            "ccgtt" => self.aacgg += 1,
            "gcgtt" => self.aacgc += 1,
            "tcgtt" => self.aacga += 1,
            "aggtt" => self.aacct += 1,
            "cggtt" => self.aaccg += 1,
            "gggtt" => self.aaccc += 1,
            "tggtt" => self.aacca += 1,
            "atgtt" => self.aacat += 1,
            "ctgtt" => self.aacag += 1,
            "gtgtt" => self.aacac += 1,
            "ttgtt" => self.aacaa += 1,
            _ => self.other += 1,
        }
    }
    /// Core printer: writes a two-column table with the given delimiter
    pub fn fmt_with_delimiter(&self, f: &mut fmt::Formatter<'_>, delim: char) -> fmt::Result {
        // header
        writeln!(f, "context{d}count", d = delim)?;

        // contexts in the same order as your fields
        let pairs = [
            ("AACAA", self.aacaa),
            ("AACAC", self.aacac),
            ("AACAG", self.aacag),
            ("AACAT", self.aacat),
            ("AACCA", self.aacca),
            ("AACCC", self.aaccc),
            ("AACCG", self.aaccg),
            ("AACCT", self.aacct),
            ("AACGA", self.aacga),
            ("AACGC", self.aacgc),
            ("AACGG", self.aacgg),
            ("AACGT", self.aacgt),
            ("AACTA", self.aacta),
            ("AACTC", self.aactc),
            ("AACTG", self.aactg),
            ("AACTT", self.aactt),
            ("AATAA", self.aataa),
            ("AATAC", self.aatac),
            ("AATAG", self.aatag),
            ("AATAT", self.aatat),
            ("AATCA", self.aatca),
            ("AATCC", self.aatcc),
            ("AATCG", self.aatcg),
            ("AATCT", self.aatct),
            ("AATGA", self.aatga),
            ("AATGC", self.aatgc),
            ("AATGG", self.aatgg),
            ("AATGT", self.aatgt),
            ("AATTA", self.aatta),
            ("AATTC", self.aattc),
            ("AATTG", self.aattg),
            ("AATTT", self.aattt),
            ("ACCAA", self.accaa),
            ("ACCAC", self.accac),
            ("ACCAG", self.accag),
            ("ACCAT", self.accat),
            ("ACCCA", self.accca),
            ("ACCCC", self.acccc),
            ("ACCCG", self.acccg),
            ("ACCCT", self.accct),
            ("ACCGA", self.accga),
            ("ACCGC", self.accgc),
            ("ACCGG", self.accgg),
            ("ACCGT", self.accgt),
            ("ACCTA", self.accta),
            ("ACCTC", self.acctc),
            ("ACCTG", self.acctg),
            ("ACCTT", self.acctt),
            ("ACTAA", self.actaa),
            ("ACTAC", self.actac),
            ("ACTAG", self.actag),
            ("ACTAT", self.actat),
            ("ACTCA", self.actca),
            ("ACTCC", self.actcc),
            ("ACTCG", self.actcg),
            ("ACTCT", self.actct),
            ("ACTGA", self.actga),
            ("ACTGC", self.actgc),
            ("ACTGG", self.actgg),
            ("ACTGT", self.actgt),
            ("ACTTA", self.actta),
            ("ACTTC", self.acttc),
            ("ACTTG", self.acttg),
            ("ACTTT", self.acttt),
            ("AGCAA", self.agcaa),
            ("AGCAC", self.agcac),
            ("AGCAG", self.agcag),
            ("AGCAT", self.agcat),
            ("AGCCA", self.agcca),
            ("AGCCC", self.agccc),
            ("AGCCG", self.agccg),
            ("AGCCT", self.agcct),
            ("AGCGA", self.agcga),
            ("AGCGC", self.agcgc),
            ("AGCGG", self.agcgg),
            ("AGCGT", self.agcgt),
            ("AGCTA", self.agcta),
            ("AGCTC", self.agctc),
            ("AGCTG", self.agctg),
            ("AGCTT", self.agctt),
            ("AGTAA", self.agtaa),
            ("AGTAC", self.agtac),
            ("AGTAG", self.agtag),
            ("AGTAT", self.agtat),
            ("AGTCA", self.agtca),
            ("AGTCC", self.agtcc),
            ("AGTCG", self.agtcg),
            ("AGTCT", self.agtct),
            ("AGTGA", self.agtga),
            ("AGTGC", self.agtgc),
            ("AGTGG", self.agtgg),
            ("AGTGT", self.agtgt),
            ("AGTTA", self.agtta),
            ("AGTTC", self.agttc),
            ("AGTTG", self.agttg),
            ("AGTTT", self.agttt),
            ("ATCAA", self.atcaa),
            ("ATCAC", self.atcac),
            ("ATCAG", self.atcag),
            ("ATCAT", self.atcat),
            ("ATCCA", self.atcca),
            ("ATCCC", self.atccc),
            ("ATCCG", self.atccg),
            ("ATCCT", self.atcct),
            ("ATCGA", self.atcga),
            ("ATCGC", self.atcgc),
            ("ATCGG", self.atcgg),
            ("ATCGT", self.atcgt),
            ("ATCTA", self.atcta),
            ("ATCTC", self.atctc),
            ("ATCTG", self.atctg),
            ("ATCTT", self.atctt),
            ("ATTAA", self.attaa),
            ("ATTAC", self.attac),
            ("ATTAG", self.attag),
            ("ATTAT", self.attat),
            ("ATTCA", self.attca),
            ("ATTCC", self.attcc),
            ("ATTCG", self.attcg),
            ("ATTCT", self.attct),
            ("ATTGA", self.attga),
            ("ATTGC", self.attgc),
            ("ATTGG", self.attgg),
            ("ATTGT", self.attgt),
            ("ATTTA", self.attta),
            ("ATTTC", self.atttc),
            ("ATTTG", self.atttg),
            ("ATTTT", self.atttt),
            ("CACAA", self.cacaa),
            ("CACAC", self.cacac),
            ("CACAG", self.cacag),
            ("CACAT", self.cacat),
            ("CACCA", self.cacca),
            ("CACCC", self.caccc),
            ("CACCG", self.caccg),
            ("CACCT", self.cacct),
            ("CACGA", self.cacga),
            ("CACGC", self.cacgc),
            ("CACGG", self.cacgg),
            ("CACGT", self.cacgt),
            ("CACTA", self.cacta),
            ("CACTC", self.cactc),
            ("CACTG", self.cactg),
            ("CACTT", self.cactt),
            ("CATAA", self.cataa),
            ("CATAC", self.catac),
            ("CATAG", self.catag),
            ("CATAT", self.catat),
            ("CATCA", self.catca),
            ("CATCC", self.catcc),
            ("CATCG", self.catcg),
            ("CATCT", self.catct),
            ("CATGA", self.catga),
            ("CATGC", self.catgc),
            ("CATGG", self.catgg),
            ("CATGT", self.catgt),
            ("CATTA", self.catta),
            ("CATTC", self.cattc),
            ("CATTG", self.cattg),
            ("CATTT", self.cattt),
            ("CCCAA", self.cccaa),
            ("CCCAC", self.cccac),
            ("CCCAG", self.cccag),
            ("CCCAT", self.cccat),
            ("CCCCA", self.cccca),
            ("CCCCC", self.ccccc),
            ("CCCCG", self.ccccg),
            ("CCCCT", self.cccct),
            ("CCCGA", self.cccga),
            ("CCCGC", self.cccgc),
            ("CCCGG", self.cccgg),
            ("CCCGT", self.cccgt),
            ("CCCTA", self.cccta),
            ("CCCTC", self.ccctc),
            ("CCCTG", self.ccctg),
            ("CCCTT", self.ccctt),
            ("CCTAA", self.cctaa),
            ("CCTAC", self.cctac),
            ("CCTAG", self.cctag),
            ("CCTAT", self.cctat),
            ("CCTCA", self.cctca),
            ("CCTCC", self.cctcc),
            ("CCTCG", self.cctcg),
            ("CCTCT", self.cctct),
            ("CCTGA", self.cctga),
            ("CCTGC", self.cctgc),
            ("CCTGG", self.cctgg),
            ("CCTGT", self.cctgt),
            ("CCTTA", self.cctta),
            ("CCTTC", self.ccttc),
            ("CCTTG", self.ccttg),
            ("CCTTT", self.ccttt),
            ("CGCAA", self.cgcaa),
            ("CGCAC", self.cgcac),
            ("CGCAG", self.cgcag),
            ("CGCAT", self.cgcat),
            ("CGCCA", self.cgcca),
            ("CGCCC", self.cgccc),
            ("CGCCG", self.cgccg),
            ("CGCCT", self.cgcct),
            ("CGCGA", self.cgcga),
            ("CGCGC", self.cgcgc),
            ("CGCGG", self.cgcgg),
            ("CGCGT", self.cgcgt),
            ("CGCTA", self.cgcta),
            ("CGCTC", self.cgctc),
            ("CGCTG", self.cgctg),
            ("CGCTT", self.cgctt),
            ("CGTAA", self.cgtaa),
            ("CGTAC", self.cgtac),
            ("CGTAG", self.cgtag),
            ("CGTAT", self.cgtat),
            ("CGTCA", self.cgtca),
            ("CGTCC", self.cgtcc),
            ("CGTCG", self.cgtcg),
            ("CGTCT", self.cgtct),
            ("CGTGA", self.cgtga),
            ("CGTGC", self.cgtgc),
            ("CGTGG", self.cgtgg),
            ("CGTGT", self.cgtgt),
            ("CGTTA", self.cgtta),
            ("CGTTC", self.cgttc),
            ("CGTTG", self.cgttg),
            ("CGTTT", self.cgttt),
            ("CTCAA", self.ctcaa),
            ("CTCAC", self.ctcac),
            ("CTCAG", self.ctcag),
            ("CTCAT", self.ctcat),
            ("CTCCA", self.ctcca),
            ("CTCCC", self.ctccc),
            ("CTCCG", self.ctccg),
            ("CTCCT", self.ctcct),
            ("CTCGA", self.ctcga),
            ("CTCGC", self.ctcgc),
            ("CTCGG", self.ctcgg),
            ("CTCGT", self.ctcgt),
            ("CTCTA", self.ctcta),
            ("CTCTC", self.ctctc),
            ("CTCTG", self.ctctg),
            ("CTCTT", self.ctctt),
            ("CTTAA", self.cttaa),
            ("CTTAC", self.cttac),
            ("CTTAG", self.cttag),
            ("CTTAT", self.cttat),
            ("CTTCA", self.cttca),
            ("CTTCC", self.cttcc),
            ("CTTCG", self.cttcg),
            ("CTTCT", self.cttct),
            ("CTTGA", self.cttga),
            ("CTTGC", self.cttgc),
            ("CTTGG", self.cttgg),
            ("CTTGT", self.cttgt),
            ("CTTTA", self.cttta),
            ("CTTTC", self.ctttc),
            ("CTTTG", self.ctttg),
            ("CTTTT", self.ctttt),
            ("GACAA", self.gacaa),
            ("GACAC", self.gacac),
            ("GACAG", self.gacag),
            ("GACAT", self.gacat),
            ("GACCA", self.gacca),
            ("GACCC", self.gaccc),
            ("GACCG", self.gaccg),
            ("GACCT", self.gacct),
            ("GACGA", self.gacga),
            ("GACGC", self.gacgc),
            ("GACGG", self.gacgg),
            ("GACGT", self.gacgt),
            ("GACTA", self.gacta),
            ("GACTC", self.gactc),
            ("GACTG", self.gactg),
            ("GACTT", self.gactt),
            ("GATAA", self.gataa),
            ("GATAC", self.gatac),
            ("GATAG", self.gatag),
            ("GATAT", self.gatat),
            ("GATCA", self.gatca),
            ("GATCC", self.gatcc),
            ("GATCG", self.gatcg),
            ("GATCT", self.gatct),
            ("GATGA", self.gatga),
            ("GATGC", self.gatgc),
            ("GATGG", self.gatgg),
            ("GATGT", self.gatgt),
            ("GATTA", self.gatta),
            ("GATTC", self.gattc),
            ("GATTG", self.gattg),
            ("GATTT", self.gattt),
            ("GCCAA", self.gccaa),
            ("GCCAC", self.gccac),
            ("GCCAG", self.gccag),
            ("GCCAT", self.gccat),
            ("GCCCA", self.gccca),
            ("GCCCC", self.gcccc),
            ("GCCCG", self.gcccg),
            ("GCCCT", self.gccct),
            ("GCCGA", self.gccga),
            ("GCCGC", self.gccgc),
            ("GCCGG", self.gccgg),
            ("GCCGT", self.gccgt),
            ("GCCTA", self.gccta),
            ("GCCTC", self.gcctc),
            ("GCCTG", self.gcctg),
            ("GCCTT", self.gcctt),
            ("GCTAA", self.gctaa),
            ("GCTAC", self.gctac),
            ("GCTAG", self.gctag),
            ("GCTAT", self.gctat),
            ("GCTCA", self.gctca),
            ("GCTCC", self.gctcc),
            ("GCTCG", self.gctcg),
            ("GCTCT", self.gctct),
            ("GCTGA", self.gctga),
            ("GCTGC", self.gctgc),
            ("GCTGG", self.gctgg),
            ("GCTGT", self.gctgt),
            ("GCTTA", self.gctta),
            ("GCTTC", self.gcttc),
            ("GCTTG", self.gcttg),
            ("GCTTT", self.gcttt),
            ("GGCAA", self.ggcaa),
            ("GGCAC", self.ggcac),
            ("GGCAG", self.ggcag),
            ("GGCAT", self.ggcat),
            ("GGCCA", self.ggcca),
            ("GGCCC", self.ggccc),
            ("GGCCG", self.ggccg),
            ("GGCCT", self.ggcct),
            ("GGCGA", self.ggcga),
            ("GGCGC", self.ggcgc),
            ("GGCGG", self.ggcgg),
            ("GGCGT", self.ggcgt),
            ("GGCTA", self.ggcta),
            ("GGCTC", self.ggctc),
            ("GGCTG", self.ggctg),
            ("GGCTT", self.ggctt),
            ("GGTAA", self.ggtaa),
            ("GGTAC", self.ggtac),
            ("GGTAG", self.ggtag),
            ("GGTAT", self.ggtat),
            ("GGTCA", self.ggtca),
            ("GGTCC", self.ggtcc),
            ("GGTCG", self.ggtcg),
            ("GGTCT", self.ggtct),
            ("GGTGA", self.ggtga),
            ("GGTGC", self.ggtgc),
            ("GGTGG", self.ggtgg),
            ("GGTGT", self.ggtgt),
            ("GGTTA", self.ggtta),
            ("GGTTC", self.ggttc),
            ("GGTTG", self.ggttg),
            ("GGTTT", self.ggttt),
            ("GTCAA", self.gtcaa),
            ("GTCAC", self.gtcac),
            ("GTCAG", self.gtcag),
            ("GTCAT", self.gtcat),
            ("GTCCA", self.gtcca),
            ("GTCCC", self.gtccc),
            ("GTCCG", self.gtccg),
            ("GTCCT", self.gtcct),
            ("GTCGA", self.gtcga),
            ("GTCGC", self.gtcgc),
            ("GTCGG", self.gtcgg),
            ("GTCGT", self.gtcgt),
            ("GTCTA", self.gtcta),
            ("GTCTC", self.gtctc),
            ("GTCTG", self.gtctg),
            ("GTCTT", self.gtctt),
            ("GTTAA", self.gttaa),
            ("GTTAC", self.gttac),
            ("GTTAG", self.gttag),
            ("GTTAT", self.gttat),
            ("GTTCA", self.gttca),
            ("GTTCC", self.gttcc),
            ("GTTCG", self.gttcg),
            ("GTTCT", self.gttct),
            ("GTTGA", self.gttga),
            ("GTTGC", self.gttgc),
            ("GTTGG", self.gttgg),
            ("GTTGT", self.gttgt),
            ("GTTTA", self.gttta),
            ("GTTTC", self.gtttc),
            ("GTTTG", self.gtttg),
            ("GTTTT", self.gtttt),
            ("TACAA", self.tacaa),
            ("TACAC", self.tacac),
            ("TACAG", self.tacag),
            ("TACAT", self.tacat),
            ("TACCA", self.tacca),
            ("TACCC", self.taccc),
            ("TACCG", self.taccg),
            ("TACCT", self.tacct),
            ("TACGA", self.tacga),
            ("TACGC", self.tacgc),
            ("TACGG", self.tacgg),
            ("TACGT", self.tacgt),
            ("TACTA", self.tacta),
            ("TACTC", self.tactc),
            ("TACTG", self.tactg),
            ("TACTT", self.tactt),
            ("TATAA", self.tataa),
            ("TATAC", self.tatac),
            ("TATAG", self.tatag),
            ("TATAT", self.tatat),
            ("TATCA", self.tatca),
            ("TATCC", self.tatcc),
            ("TATCG", self.tatcg),
            ("TATCT", self.tatct),
            ("TATGA", self.tatga),
            ("TATGC", self.tatgc),
            ("TATGG", self.tatgg),
            ("TATGT", self.tatgt),
            ("TATTA", self.tatta),
            ("TATTC", self.tattc),
            ("TATTG", self.tattg),
            ("TATTT", self.tattt),
            ("TCCAA", self.tccaa),
            ("TCCAC", self.tccac),
            ("TCCAG", self.tccag),
            ("TCCAT", self.tccat),
            ("TCCCA", self.tccca),
            ("TCCCC", self.tcccc),
            ("TCCCG", self.tcccg),
            ("TCCCT", self.tccct),
            ("TCCGA", self.tccga),
            ("TCCGC", self.tccgc),
            ("TCCGG", self.tccgg),
            ("TCCGT", self.tccgt),
            ("TCCTA", self.tccta),
            ("TCCTC", self.tcctc),
            ("TCCTG", self.tcctg),
            ("TCCTT", self.tcctt),
            ("TCTAA", self.tctaa),
            ("TCTAC", self.tctac),
            ("TCTAG", self.tctag),
            ("TCTAT", self.tctat),
            ("TCTCA", self.tctca),
            ("TCTCC", self.tctcc),
            ("TCTCG", self.tctcg),
            ("TCTCT", self.tctct),
            ("TCTGA", self.tctga),
            ("TCTGC", self.tctgc),
            ("TCTGG", self.tctgg),
            ("TCTGT", self.tctgt),
            ("TCTTA", self.tctta),
            ("TCTTC", self.tcttc),
            ("TCTTG", self.tcttg),
            ("TCTTT", self.tcttt),
            ("TGCAA", self.tgcaa),
            ("TGCAC", self.tgcac),
            ("TGCAG", self.tgcag),
            ("TGCAT", self.tgcat),
            ("TGCCA", self.tgcca),
            ("TGCCC", self.tgccc),
            ("TGCCG", self.tgccg),
            ("TGCCT", self.tgcct),
            ("TGCGA", self.tgcga),
            ("TGCGC", self.tgcgc),
            ("TGCGG", self.tgcgg),
            ("TGCGT", self.tgcgt),
            ("TGCTA", self.tgcta),
            ("TGCTC", self.tgctc),
            ("TGCTG", self.tgctg),
            ("TGCTT", self.tgctt),
            ("TGTAA", self.tgtaa),
            ("TGTAC", self.tgtac),
            ("TGTAG", self.tgtag),
            ("TGTAT", self.tgtat),
            ("TGTCA", self.tgtca),
            ("TGTCC", self.tgtcc),
            ("TGTCG", self.tgtcg),
            ("TGTCT", self.tgtct),
            ("TGTGA", self.tgtga),
            ("TGTGC", self.tgtgc),
            ("TGTGG", self.tgtgg),
            ("TGTGT", self.tgtgt),
            ("TGTTA", self.tgtta),
            ("TGTTC", self.tgttc),
            ("TGTTG", self.tgttg),
            ("TGTTT", self.tgttt),
            ("TTCAA", self.ttcaa),
            ("TTCAC", self.ttcac),
            ("TTCAG", self.ttcag),
            ("TTCAT", self.ttcat),
            ("TTCCA", self.ttcca),
            ("TTCCC", self.ttccc),
            ("TTCCG", self.ttccg),
            ("TTCCT", self.ttcct),
            ("TTCGA", self.ttcga),
            ("TTCGC", self.ttcgc),
            ("TTCGG", self.ttcgg),
            ("TTCGT", self.ttcgt),
            ("TTCTA", self.ttcta),
            ("TTCTC", self.ttctc),
            ("TTCTG", self.ttctg),
            ("TTCTT", self.ttctt),
            ("TTTAA", self.tttaa),
            ("TTTAC", self.tttac),
            ("TTTAG", self.tttag),
            ("TTTAT", self.tttat),
            ("TTTCA", self.tttca),
            ("TTTCC", self.tttcc),
            ("TTTCG", self.tttcg),
            ("TTTCT", self.tttct),
            ("TTTGA", self.tttga),
            ("TTTGC", self.tttgc),
            ("TTTGG", self.tttgg),
            ("TTTGT", self.tttgt),
            ("TTTTA", self.tttta),
            ("TTTTC", self.ttttc),
            ("TTTTG", self.ttttg),
            ("TTTTT", self.ttttt),
            ("other", self.other),
        ];

        for &(ctx, cnt) in &pairs {
            writeln!(f, "{ctx}{d}{cnt}", d = delim)?;
        }
        Ok(())
    }
}

impl fmt::Display for CountsPenta {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // default to tab-delimited
        self.fmt_with_delimiter(f, '\t')
    }
}

#[derive(Default, Debug)]
pub struct CountsDi {
    ac: u64,
    at: u64,
    cc: u64,
    cg: u64,
    ct: u64,
    gc: u64,
    ta: u64,
    tc: u64,
    tg: u64,
    tt: u64,
    other: u64,
}

impl CountsDi {
    pub fn increment(&mut self, di: &str) {
        // Change to Uppercase
        let di_lower = di.to_ascii_lowercase();
        match di_lower.as_str() {
            // Normal Doublets
            "ac" => self.ac += 1,
            "at" => self.at += 1,
            "cc" => self.cc += 1,
            "cg" => self.cg += 1,
            "ct" => self.ct += 1,
            "gc" => self.gc += 1,
            "ta" => self.ta += 1,
            "tc" => self.tc += 1,
            "tg" => self.tg += 1,
            "tt" => self.tt += 1,
            // Reverse Complements
            "gt" => self.ac += 1,
            "gg" => self.cc += 1,
            "ag" => self.ct += 1,
            "ga" => self.tc += 1,
            "ca" => self.tg += 1,
            "aa" => self.tt += 1,
            _ => self.other += 1,
        }
    }

    pub fn fmt_with_delimiter(&self, f: &mut fmt::Formatter<'_>, delim: char) -> fmt::Result {
        // header
        writeln!(f, "context{d}count", d = delim)?;

        // contexts in the same order as your fields
        let pairs = [
            ("ac", self.ac),
            ("at", self.at),
            ("cc", self.cc),
            ("cg", self.cg),
            ("ct", self.ct),
            ("gc", self.gc),
            ("ta", self.ta),
            ("tc", self.tc),
            ("tg", self.tg),
            ("tt", self.tt),
            ("other", self.other),
        ];

        for &(ctx, cnt) in &pairs {
            writeln!(f, "{ctx}{d}{cnt}", d = delim)?;
        }
        Ok(())
    }
}

impl fmt::Display for CountsDi {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // default to tab-delimited
        self.fmt_with_delimiter(f, '\t')
    }
}
